##Script to visualise population structure##

# Load packages

library("tidyverse")
library("dplyr")
library("ggplot2")
library("readxl")
library("plotly")
library("ggthemes")
library("paletteer")

        ####################
        ######PCAngsd#######
        ####################

# Set colour palette

col_palette <- c(paletteer_d("ggthemes::Red_Blue_Brown")[12],
                 paletteer_d("ggthemes::Summer")[7],
                 paletteer_d("ggthemes::Green_Orange_Teal")[2],
                 paletteer_d("ggthemes::Winter")[9],
                 paletteer_d("ggthemes::Red_Blue_Brown")[2],
                 paletteer_d("ggthemes::Purple_Pink_Gray")[12])

# Read in co-variance matrix generated by PCAngsd
cov <- as.matrix(read.table("WSD_GLs.cov"))

# Read in info file with population assignments
Region <- read.table("pop_file.info",as.is = T)

# Compute eigenvalues
e <- eigen(cov)

mycol <- as.factor(Region$V1)

pc <- e$vectors[,1:2]
pc2 <- e$vectors[,2:3]
pca <- as.data.frame(pc)
pca2 <- as.data.frame(pc2)
pca_pop <- cbind(pca, Region)
pca_pop2 <- cbind(pca2, Region)
colnames(pca_pop) <- c("PC1", "PC2", "Region", "id")
colnames(pca_pop2) <- c("PC1", "PC3", "Region", "id")

# Sum of eigenvalues
pca.eigenval.sum = sum(e$values)

varPC1 <- (e$values[1]/pca.eigenval.sum)*100
VarPc2 <- (e$values[2]/pca.eigenval.sum)*100
VarPC3 <- (e$values[3]/pca.eigenval.sum)*100
VarPC4 <- (e$values[4]/pca.eigenval.sum)*100

# Plot PC1 and PC2
PCA_plot <- ggplot(pca_pop) +
  aes(x = PC1, y = PC2, col=Region) +
  scale_color_manual(values = col_palette) +
  geom_point(shape = ifelse(1:nrow(pca_pop) == 83, 17, 19), size = 3) +
  xlab(paste0("PC1 ", "(", round((e$values[1]/pca.eigenval.sum)*100), "%)")) +
  ylab(paste0("PC2 ", "(", round((e$values[2]/pca.eigenval.sum)*100), "%)")) +
  labs(title = "B") +
  theme_few()

plot(PCA_plot)

ggsave("figures/Figure2B.png", PCA_plot, width = 7, height = 9)

# Plot PC1 and PC3
PCA_plot2 <- ggplot(pca_pop2) +
  aes(x = PC1, y = PC3, col=Region) +
  scale_color_manual(values = col_palette) +
  geom_point(shape = ifelse(1:nrow(pca_pop) == 83, 17, 19), size = 3) +
  xlab(paste0("PC1 ", "(", round((e$values[1]/pca.eigenval.sum)*100), "%)")) +
  ylab(paste0("PC3 ", "(", round((e$values[3]/pca.eigenval.sum)*100), "%)")) +
  labs(title = "B") +
  theme_few()

plot(PCA_plot2)

ggsave("figures/FigureS5.png", PCA_plot2, width = 7, height = 9)

# Create interactive map
ggplotly(PCA_plot) 
